const startQuestions = [
    {   id: '1',
        author: 'Vlada',
        var1: 'sleep',
        var2: 'dance',
    },
    {   id: '2',
        author: 'Vlada',
        var1: 'day',
        var2: 'night',
    },
    {   id: '3',
        author: 'Vlada',
        var1: 'tea',
        var2: 'coffee',
    },
    {   id: '4',
        author: 'Vlada',
        var1: 'boys',
        var2: 'girls',
    },
    {   id: '5',
        author: 'Vlada',
        var1: 'BMW',
        var2: 'Mercedes',
    },
    {   id: '6',
        author: 'Vlada',
        var1: 'Batman',
        var2: 'Superman',
    },
]

export default startQuestions